### ISSUE TITLE
Going public

### ISSUE THREAD

**Issue by bartkrekelberg** [klabhub/neurostim#110]
Should we make the repo public? 

- [ ] Change the name to neurostim (without the ptb)
- [ ] Need some rudimentary documentation in the Readme.md
- [ ] Add a wiki

**Comment by bartkrekelberg** [comment]
Done. 

We're now https://github.com/klabhub/neurostim  


@cnuahs  Forks are disconnected- you may have to re-fork.

**Comment by duijnhouwer** [comment]
That’s cool, v1.0! Congratulations. I hope people find good use for it. MIT
license can be used freely for commercial purposes at, say, Magic Leap Inc,
too?
Jacob
