### ISSUE TITLE
Reading a private property of movie.m

### ISSUE THREAD

**Issue by dshimaoka** [klabhub/neurostim#179]
To trigger a digital signal at a desired condition, I wish to access a private property (`fracFrameCntr`) inside an eScript. 

One way to do this is to change this property to `GetAccess = public` and `SetAccess = private`.

Another way is to make a function like below:
 ```
methods (Access = public)
        function v = getFracFrameCntr(o)
            v = o.fracFrameCntr;
        end
```

Which way is more preferable?

**Comment by bartkrekelberg** [comment]
For this purpose (public read access only) just changing the property GetAccess/SetAccess is the right way to do it.

**Comment by dshimaoka** [comment]
thanks for the suggestion. A new pull request will soon follow.
