### ISSUE TITLE
MCC digitalOut bit setting is slow

### ISSUE THREAD

**Issue by nicholasprice** [klabhub/neurostim#198]
The digitalOut function in the [mcc plugin](https://github.com/klabhub/neurostim/blob/master/%2Bneurostim/%2Bplugins/mcc.m) has two options:

1. write a byte, which is fast, but could upset lines set by other plugins
2. write a bit, which first polls the current state of the outputs.
Polling the current state with DaqDIn is unacceptably slow (>2 frames dropped in my tests). A possible fix is to store the current digital output value as a parameter in the object. I'm happy to implement this approach if nobody can see a drawback.

**Comment by bartkrekelberg** [comment]
See PR #185
