### ISSUE TITLE
noiseclut.samplefun error

### ISSUE THREAD

**Issue by dshimaoka** [klabhub/neurostim#201]
There is a case when noiseclut.samplefun is not a cell array, which creates an error at l.232 of noiseclut.m
To avoid this, one workaround would be to add the following just prior to l.232 as:
                if ~iscell(o.sampleFun) 
                    o.sampleFun = {o.sampleFun};  
                end

**Comment by adammorrissirrommada** [comment]
Agreed, can you please make the change and issue a pull request?
