### ISSUE TITLE
Saving ns data

### ISSUE THREAD

**Issue by adammorrissirrommada** [klabhub/neurostim#81]
Our current approach is to save the cic object as our data file. This is nice, and has many advantages. But a downside is that it is an instance of a class at a certain point in time, and so if the associated class definition is later changed in a way that conflicts with the object, it doesn't load properly. For example, a property might be entirely missing. As long as the ns code was at a particular commit with no local changes, it would be possible to revert to that state to load in the data. But perhaps we should also store the logs in a text format as a fail-safe? Have you encountered this problem or given this any thought @bartkrekelberg?

**Comment by bartkrekelberg** [comment]
Continue the discussion in #170
